os:
  editPreset: "nvim"
git:
  # If true, periodically fetch from remote
  autoFetch: false
  # If true, periodically refresh files and submodules
  autoRefresh: false
  log:
    showSignature: false
  diffRenderers:
    - colorArg: always
      command: delta --paging=never
refresher:
  refreshInterval: 10
  fetchInterval: 0
# Periodic update checks
update:
  # One of: 'prompt' (default) | 'background' | 'never'
  method: prompt
  # Period in days between update checks
  days: 14
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#ff9e64"
      - "bold"
    inactiveBorderColor:
      - "#29a4bd"
    searchingActiveBorderColor:
      - "#ff9e64"
      - "bold"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#2e3c64"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    cherryPickedCommitBgColor:
      - "#bb9af7"
    markedBaseCommitFgColor:
      - "#7aa2f7"
    markedBaseCommitBgColor:
      - "#e0af68"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
customCommands:
  - key: "S"
    context: "global"
    command: "git pull --rebase && git push"
    description: "Sync: pull (rebase) then push"
    loadingText: "Syncing..."
